apiVersion: v1
kind: ConfigMap
metadata:
  name: scaling-options
  namespace: scaler
data:
  workloads.csv: |
    workloadName,ns,defReplicas,maxReplicas,maxReplyTime,maxCurPerPod,stabilizationWindowDown,stabilizationWindowUp,scaleFactor
    name,namespace,2,15,0.6,20,30,2,2